language: node_js
node_js:
- '0.11'
before_install:
- npm install browserify -g
install:
- npm install
before_script:
- npm link .
script:
- npm run build
- npm run test
- npm run cover
- npm run report
env:
  global:
    secure: T/clBdNyqsLMpJWDDnHOOvjEwrJaTHxKQJeaGL3tE0v295knlBNm2LzjcS5t0oWXCwXJLVGyfs/tRJr1EWnYcpkqy8PCyoZA/0E+S1EIDU0pG6ySpCWATI9pyx9tzASUjcHrWaD7mhmP4gLooSgNjt9e/F6/1yR4BCSwazgFe9d9QhvcAM6XdUnkvzc51QgPKxWesZUYT0iZntFROM8QIrkm9IWSuRc3egWXYviBWC9X/0lm6uYV8ttGTSWkVoJeyhm9HvGd9hbZaN0vyQBJ0vw1oxQB4a4sHFTBai6CDSbh7xeLJI9+lamJr9jd9Sz0IF8PU0zkyz0XziD4ZK7px1FGeanFZHRQJX6v2n8rC+fxNT/wpBTJ2LAfpVC71y8rpGXB2j+npH9wUlPgN9le4hXDpDukMhCXSwzEX3gRoYQuUy0GpUBt4W0L03MLlD8n1YNNfN1RfpvA+B5duZg+Ztc2euhHn+Wn21ASy76R9XgqX0N7EMChn3vDLLxttz94hcWFZhQI0yvLy1YovNrnPLMVygog3fq8/6T9vcfmctJeA9s/FBFBKXSqDLhYCz6hrCqMcAAGzuJGBvSjtFdLiSySPHkfIOQzfspQeRYt04ds/e4yKLUxf8NhFNNnX56JFZpekYHp2tXGZNFJfCL+oJUzHKSXsI7856X7l+I6QCQ=
